// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js keeps env vars in .env.local; load it (then .env) so the Prisma CLI
// sees DIRECT_URL/DATABASE_URL the same way the dev server does.
dotenv.config({ path: ".env.local" });
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use the direct (session-pooler) URL.
    url: process.env["DIRECT_URL"],
  },
});
